### ISSUE TITLE
beam search

### ISSUE THREAD

**Issue by asmartsnail** [Sundrops/video-caption.pytorch#1]
这个beam search是不是写的有问题啊?

**Comment by Sundrops** [comment]
目前我自己的测试是没问题的 有什么问题你可以具体指出

**Comment by asmartsnail** [comment]
在DecoderRnn.py里面下面这行
![image](https://user-images.githubusercontent.com/18095758/45808847-614b3f00-bcf9-11e8-9230-580c7081cb85.png)
x[1]应该是一个batch size维的Tensor吧,直接转int,然后比较不会出问题么,我是用的python3,cmp在python3里面有问题,我改了下好像不太对,不知道是不是我理解的有问题.

**Comment by Sundrops** [comment]
我是在py2下测试的 具体代码细节我已经记不得了 我之前是能正常跑通而且效果是有不少提升的

**Comment by asmartsnail** [comment]
好的
